name: Test Dependencies

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check file path
        run: |
          ll -ltra
      - name: Checkout repository
        uses: actions/setup-node@v3
        with:
          node-version: 18
        run: npm test
      # Add build steps if needed, e.g., compiling your project

