name: Test Dependencies

on:
  push:
    

jobs:
  
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Add build steps if needed, e.g., compiling your project

  