name: Test Dependencies

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check file path
        run: |
          pwd
          ls -ltra
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: AWS Backup1
        
        run: |
          aws s3 sync s3://buckettesters44 s3://buckettesters55
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
          
      - name: AWS S3 SYNC
        run: |
          aws s3 sync ./dist s3://buckettesters44
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
       
      # Add build steps if needed, e.g., compiling your project

