name: Test Dependencies

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: Select Env
        required: true
        default: 'release'
        options:
        - release
        - build
        - stage

    

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
<<<<<<< HEAD
      contains(${{ inputs.deployment }}, 'build') || 
      (contains(${{ inputs.deployment }}, 'release') && github.ref == 'refs/heads/master') ||
      (contains(${{ inputs.deployment }}, 'stage') && github.ref == 'refs/heads/master')
=======
      contains(${{ inputs.deployment }}, build) || 
      (contains(${{ inputs.deployment }}, release) && github.ref == 'refs/heads/master') ||
      (contains(${{ inputs.deployment }}, stage) && github.ref == 'refs/heads/master')
>>>>>>> 043eec7dc5aba85c88c76f42d247a97b7e3348b2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check file path
        run: |
          pwd
          ls -ltra
          echo "xxxxxxx" > file1.txt
      
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Upload Artifact" 
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: file1.txt
      - name: Check node version
        run: |
          node -v

  release:
    needs: build
    environment:
      name: ${{ inputs.deployment }}-build
    runs-on: ubuntu-latest
    steps:
      - name: AWS Backup
        
        run: |
          aws s3 sync s3://buckettesters44 s3://buckettesters55
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
          
      - name: AWS S3 SYNC
        run: |
          aws s3 sync ./dist s3://buckettesters44
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
       
      # Add build steps if needed, e.g., compiling your project

